const RENAMED_COUNTRIES = new Map([
	["Viet Nam", "Vietnam"],
	["Venezuela (Bolivarian Republic)", "Venezuela"],
	["Holy See (Vatican City State)", "Vatican"],
	["Micronesia, Federated States of", "Micronesia"],
	["Marshall Islands", "Marshall Is."],
	["Northern Mariana Islands", "N. Mariana Is."],
	["Virgin Islands, US", "U.S. Virgin Is."],
	["Samoa", "American Samoa"],
	["Tanzania, United Republic of", "Tanzania"],
	["Taiwan, Republic of China", "Taiwan"],
	["Syrian Arab Republic (Syria)", "Syria"],
	["South Sudan", "S. Sudan"],
	["Korea (South)", "South Korea"],
	["Solomon Islands", "Solomon Is."],
	["Sao Tome and Principe", "São Tomé and Principe"],
	["Saint Vincent and Grenadines", "St. Vin. and Gren."],
	["Saint Kitts and Nevis", "St. Kitts and Nevis"],
	["Russian Federation", "Russia"],
	["Western Sahara", "W. Sahara"],
	["Macedonia, Republic of", "Macedonia"],
	["Republic of Kosovo", "Kosovo"],
	["Palestinian Territory", "Palestine"],
	["Iran, Islamic Republic of", "Iran"],
	["Equatorial Guinea", "Eq. Guinea"],
	["Dominican Republic", "Dominican Rep."],
	["Czech Republic", "Czechia"],
	["Cyprus", "N. Cyprus"],
	["Congo (Kinshasa)", "Dem. Rep. Congo"],
	["Congo (Brazzaville)", "Congo"],
	["Macao, SAR China", "Macao"],
	["Central African Republic", "Central African Rep."],
	["Brunei Darussalam", "Brunei"],
	["Bosnia and Herzegovina", "Bosnia and Herz."],
	["Antigua and Barbuda", "Antigua and Barb."],
	["Lao PDR", "Laos"],
	["Swaziland", "eSwatini"]
]);

export { RENAMED_COUNTRIES };